### ISSUE TITLE
Problems with installation (directory, start)

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [KraXen72/shira#7]
First of all I'm wondering if there's a way to have this script next to the other python scripts such as yt-dlp which are typically installed as such: `pip3 install []`. I'm not a fan of having the shira folder on my main ~ folder, and don't know how to move it elsewhere while retaining the command.

Then, when I try to start it I get as follows:

```
Last login: Fri Jun 14 16:30:13 on ttys000
redacted-iMac:~ redacted$ cd /Users/redacted/shira 
redacted-iMac:shira redacted$ shiradl
-bash: shiradl: command not found
redacted-iMac:shira redacted$ python shiradl
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/redacted/shira/shiradl/__main__.py", line 3, in <module>
    from .cli import cli
ValueError: Attempted relative import in non-package
redacted-iMac:shira redacted$ python3 shiradl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/redacted/shira/shiradl/__main__.py", line 3, in <module>
    from .cli import cli
ImportError: attempted relative import with no known parent package
redacted-iMac:shira redacted$ pip install shiradl
ERROR: Could not find a version that satisfies the requirement shiradl (from versions: none)
ERROR: No matching distribution found for shiradl
redacted-iMac:shira redacted$ pip install shiradl
```

**Comment by KraXen72** [comment]
> I'm wondering if there's a way to have this script next to the other python scripts such as yt-dlp which are typically installed as such: pip3 install []. I'm not a fan of having the shira folder on my main ~ folder, and don't know how to move it elsewhere while retaining the command.

for now there's no such way, but once #2 is resolved, it'll be possible. please wait until then or make a pull request.

>Then, when I try to start it I get as follows:
  
please see [usage examples](https://github.com/KraXen72/shira#usage-examples) in the readme. you have to do `python -m shiradl <whatever>`
